import { createClient, SupabaseClient } from '@supabase/supabase-js'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || ''
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY || ''

// Only create client if valid credentials are provided
const isValidUrl = (url: string) => {
  try {
    const parsed = new URL(url)
    return parsed.protocol === 'http:' || parsed.protocol === 'https:'
  } catch {
    return false
  }
}

let supabaseClient: SupabaseClient | null = null

if (isValidUrl(supabaseUrl) && supabaseAnonKey.length > 0) {
  supabaseClient = createClient(supabaseUrl, supabaseAnonKey)
}

function getSupabaseClient() {
  if (!supabaseClient) {
    throw new Error('Supabase client not configured. Please set NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY environment variables.')
  }
  return supabaseClient
}

// Helper function to submit customer requests
export async function submitCustomerRequest(formData: {
  name: string
  phone: string
  location: string
  customCity?: string
  preferences: string[]
  priceRange: string
  basketItems?: Array<{
    id: string
    productId: string
    productName: string
    brandId: string
    brandName: string
    category: string
    price: number
    image?: string
  }>
}) {
  const supabase = getSupabaseClient()

  const payload = {
    name: formData.name,
    phone: formData.phone,
    location: formData.location === 'Other' ? formData.customCity : formData.location,
    preferences: formData.preferences,
    price_range: formData.priceRange,
    basket_items: formData.basketItems || [],
    source_page: 'customer_landing',
    // created_at will be auto-generated by Supabase with default now()
  }

  const { data, error } = await supabase
    .from('customer_requests')
    .insert([payload])
    .select()

  if (error) {
    throw new Error(error.message)
  }

  return data
}

// Helper function to submit brand partnership requests
export async function submitBrandRequest(formData: {
  contactName: string
  title: string
  email: string
  phone: string
  brandName: string
  websiteUrl: string
  countryOfOrigin: string
  productTypes: string[]
  pricePoint: string
  numberOfSKUs: string
  sellsVia: string
  hasMiddleEastPresence: string
  middleEastPresenceDetails?: string
  instagramHandle?: string
}) {
  const supabase = getSupabaseClient()

  const payload = {
    contact_name: formData.contactName,
    title: formData.title,
    email: formData.email,
    phone: formData.phone,
    brand_name: formData.brandName,
    website_url: formData.websiteUrl,
    country_of_origin: formData.countryOfOrigin,
    product_types: formData.productTypes,
    price_point: formData.pricePoint,
    number_of_skus: parseInt(formData.numberOfSKUs, 10),
    sells_via: formData.sellsVia,
    has_middle_east_presence: formData.hasMiddleEastPresence === 'yes',
    middle_east_presence_details: formData.middleEastPresenceDetails || null,
    instagram_handle: formData.instagramHandle || null,
    source_page: 'brand_landing',
    // created_at will be auto-generated by Supabase with default now()
  }

  const { data, error } = await supabase
    .from('brand_requests')
    .insert([payload])
    .select()

  if (error) {
    throw new Error(error.message)
  }

  return data
}
